#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApplication.Resource", IsApplication=true)]

namespace AndroidApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EditText = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Label = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int AddButton = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int AddConnectionButton = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int CodeEditText = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int SelectPhotoButton = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int image = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int mylistview = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int text = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int toolbar = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddConnection = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListView_Row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ToolBar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int MyTheme = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int button_text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int edittext_text = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
